### ISSUE TITLE
Null monomers appear in the monomer list

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#120]
When I look at my set of monomers I see a 'null' monomer. 

![image](https://user-images.githubusercontent.com/3986896/30426608-8f3d4cd4-9944-11e7-91ba-13d2f898c731.png)
It can't be placed on the canvas. It should not be displayed.

**Comment by scilligence** [comment]
fixed in 2017-10-10 update

**Comment by ClairePA** [comment]
I still see it. 

![image](https://user-images.githubusercontent.com/3986896/31380689-efd851be-ada9-11e7-97a1-bd63ba0510c1.png)

**Comment by scilligence** [comment]
Sorry.  The previous fix is to fix "null" monomer cannot be used.  

"null" monomer is originally requested by Ionis.  We will have to confirm with them before removing it.

**Comment by ClairePA** [comment]
We do not need a null monomer here. Ambiguous monomers are handled via other means.

**Comment by scilligence** [comment]
Fixed in 2017-11-06 update

**Comment by ClairePA** [comment]
Confirmed fixed. Thanks.
