### ISSUE TITLE
2 errors are thrown when entering wrong base

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#123]
When entering a wrong sequence, for example: ATGCI as RNA in the sequence box, the application sends 2 error messages in successive popups:
- Unknown HELM_BASE monomer name: I
- Error: failed to creating node: I

I think it would be better to have just the first error as popup for the user and not have the second one.

**Comment by scilligence** [comment]
Fixed in 2017-10-17 update

**Comment by ClairePA** [comment]
Looks fixed to me. Yohann, can you confirm?

**Comment by ypotier** [comment]
Is it on the http://54.91.164.146/WebService/hwe/examples/App.htm server because I still see the error there?

**Comment by ypotier** [comment]
Tested and closed
