### ISSUE TITLE
Inconsistent nomenclature and use of the blob dialogue boxes

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#129]
If I right-click on a blob, I get a list of options for 'Blob type'

![image](https://user-images.githubusercontent.com/3986896/31380114-513c040c-ada8-11e7-8a3a-e85130e455a1.png)
If I choose 'Set Monomer Attributes' I can change the 'Monomer Type' or 'Annotation'

![image](https://user-images.githubusercontent.com/3986896/31380183-7d915fde-ada8-11e7-8a0f-ecfbc5a2af60.png)

-  You should not be able to change the monomer type since it is already set as blob. In fact the validation does not allow you to, so this box is redundant. 
- Arguably you should be able to change the blob type here, but only from a drop down list of options (basically the same as in the blob type list - see top screen-shot. The option could be removed however, since it is only repeating what is already available. 
- You must be able to add an annotation to the blob.

**Comment by scilligence** [comment]
fixed in 2017-10-31 update

**Comment by ClairePA** [comment]
I can see that it is not possible to change the monomer type now, but the rest still does not work. I think there is a misunderstanding over what each term means. 

-  The monomer type "blob" is analogous to peptide, chem etc...
- The blob type is unique to blobs. it replaces the monomers that are present in other polymer types and is limited to a set of predefined options, currently Bead, gold particle. Other options may need to be added later. 
- An annotation is separate to the blob type and is free text. 

See the definition of blobs in the HELM specification:

Unknown Polymers are marked as BLOB type polymers. These polymers do not contain a list of monomers but they specify their type inside the curly braces. The polymer BLOB1{Bead} for example represents a polymer with the type “Bead”.

Also see an example of the HELM for a peptide sequence conjugated to a gold particle in the Line Notation Design document. 

PEPTIDE1{C.C.C.C.C.C}|BLOB1{Gold Particle}”Au10,
Diameter:10nm”$PEPTIDE,BLOB1,C:R3-?:R1$G1(PEPTIDE1:20-34+BLOB1)${“Name”:”Gold particle
conjugated with peptides”,”Load”:26}$

Having a monomer type in the monomer attributes box makes little sense, as the user should simply remove the blob if they want a different type. 

![image](https://user-images.githubusercontent.com/3986896/32218157-fb4326f4-be21-11e7-80b0-b98703e18a7c.png)

However they do need the ability to select a set of blob types from a drop down list and add an actual annotation.

**Comment by ClairePA** [comment]
I can still type in the monomer type box. I can't delete the blob text, but can make the value something that is not recognised. The monomer type section of this dialogue box should be removed as it is not needed.  It won't be needed for any monomer as the monomer can be replace if the user wants to change it. 

Also, the HELM is incorrect. 
![image](https://user-images.githubusercontent.com/3986896/32452508-a7574d0a-c311-11e7-9552-b77dbb77732d.png)

In this case the HELM should be 


BLOB1{Gold Particle}"rteyre"$$$$V2.0

**Comment by scilligence** [comment]
Fixed in 2017-11-07 update

**Comment by ClairePA** [comment]
Monomer type is still present. There is no such thing as monomer type. It is the symbol.

**Comment by scilligence** [comment]
Fixed 2017-11-13

**Comment by ClairePA** [comment]
Confirmed fixed. Thanks.
