### ISSUE TITLE
Export to SMILES in Monomer manager does not do anything

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#176]
The Export option in the monomer manager allows to choose between mol and SMILES. While mol is working, the SMILES choice will remain blank.

Of course, the SMILES is available in the SMILES field so it's not a blocker but we could display the SMILES since we already have it, or remove that option.

![image](https://user-images.githubusercontent.com/8645925/39062998-78a146c0-4497-11e8-8a7f-6b14e5e21823.png)

**Comment by scilligence** [comment]
SMILES is not supported.  The option is removed in 2018-05-01 update

**Comment by ClairePA** [comment]
Confirmed OK to remove SMILES. 

Drop down list should default to molfile as there are no alternatives.

**Comment by scilligence** [comment]
Fixed 2018-05-06 update

**Comment by ClairePA** [comment]
It looks like the whole export option has been removed. I think we wanted the export to remain, but default to molfile since this is the only format available.

**Comment by ypotier** [comment]
I can still see the export, and MOL export is selected by default with the content visible. 

![image](https://user-images.githubusercontent.com/8645925/39830500-a73e5318-538f-11e8-892a-242ae246b3ef.png)

**Comment by ClairePA** [comment]
Sorry - I'm being dense and I have found it now. The import is fine, but the export doesn't default to mol and mol is the only option. Could we get this fixed?

**Comment by ClairePA** [comment]
Arrgghh having a really bad day. 

- Export is fine.
- Import needs to default to mol. 

Thanks to Yohann for pointing this out.

**Comment by scilligence** [comment]
Fixed in 2018-05-13 update
