### ISSUE TITLE
The user is not warned that they can't change a monomer's symbol

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#215]
Steps:
Edit a monomer and change the symbol.
Save the monomer
It is not updated on save and the user is not warned.

**Comment by ClairePA** [comment]
After discussion in the team meeting - the symbol box should not be editable when editing existing monomers.

**Comment by scilligence** [comment]
Fixed in 2018-10-15 update

**Comment by ClairePA** [comment]
Confirmed fixed. I still get 409 errors, but that is a different issue.
