### ISSUE TITLE
Can't create a new monomer

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#220]
I click on the + button to create a new monomer and the dialogue box appears. 
I enter information and click save.

I see the following error message.

![image](https://user-images.githubusercontent.com/3986896/46360406-42d33500-c663-11e8-9887-b6f5e626c802.png)

**Comment by AnneMund** [comment]
409 indicates a conflict, so it seems that the MonomerService (erroneously) detects that the same monomer structure has been entered before.

**Comment by ClairePA** [comment]
I just tried with several different structures including one that definitely has not been used before. I also changed the ID to symbols that have also definitely not been used before and I still get a 409 error. Any ideas?

![image](https://user-images.githubusercontent.com/3986896/46659530-ffba1a00-cbac-11e8-8fe9-980830dc1fea.png)

**Comment by AnneMund** [comment]
I've tried to track down this bug; there is a more detailed error message available via the swagger page that is not displayed in the WebEditor. The exact error message is that no smiles could be generated:
![grafik](https://user-images.githubusercontent.com/34510755/46660638-c0dd9180-cbb7-11e8-963d-0b1756f6c006.png)

I've tried the exact same structure in my local debugging environment and cannot reproduce it there, which makes tracking it down a lot harder, unfortunately.

**Comment by AnneMund** [comment]
Okay, this is strange; I've tried it again with the MonomerService deployed on a local docker instance and I'm getting different behaviour than the test server;
Docker here at quattro:
![grafik](https://user-images.githubusercontent.com/34510755/46661660-e5d30400-cbb9-11e8-83b1-703df731c902.png)

Test site at Scilligence:
![grafik](https://user-images.githubusercontent.com/34510755/46661678-eff50280-cbb9-11e8-8004-2ad66c6c3a94.png)

@scilligence Have you changed any chemistry settings, by any chance? Or is there some other configuration which could differ between the systems?

**Comment by ClairePA** [comment]
Retested using the webeditor on the new Pistoia Docker image http://webeditor.openhelm.org:8000/hwe/examples/MonomerLibApp.htm and I get the same 409 error.

**Comment by AnneMund** [comment]
This is getting really strange; I've pulled the docker file that is in use for the openhelm.org test site and deployed it at our docker host:
![grafik](https://user-images.githubusercontent.com/34510755/46816964-562a8280-cd7e-11e8-8013-ea036a042350.png)

But again, if I use the exact same input on this system as well as the openhelm.org site, I get different behaviour. It works on our docker host:
![grafik](https://user-images.githubusercontent.com/34510755/46817039-840fc700-cd7e-11e8-908f-26a27d8e329f.png)

**Comment by ClairePA** [comment]
Really odd. So you see the problem on http://webeditor.openhelm.org:8000/hwe/examples/MonomerLibApp.htm but not on yours despite the fact that they should be the same?

**Comment by AnneMund** [comment]
Yes, with the exact same docker image and input. I had to do the screenshots, because I still feel like "this should not happen".

**Comment by ClairePA** [comment]
The webservices issues have been fixed and we have the latest version of the webservices and webeditor at http://webeditor.openhelm.org:8000/hwe/examples/App.htm. 

This is now exclusively a webeditor problem. 
I create the following monomer
![image](https://user-images.githubusercontent.com/3986896/48769839-91409f80-ecb4-11e8-965a-a7544bb6fbae.png)

On clicking save in the webeditor, I get the following message:
![image](https://user-images.githubusercontent.com/3986896/48769856-9c93cb00-ecb4-11e8-81db-d4238efb00b8.png)

**Comment by scilligence** [comment]
I cannot reproduce the "Expected ';'" error above, but did get this error message:

    "Monomer has no Smiles; Smiles could not be generated from Molfile and R-Groups"

Markus -

Is there any change in the Monomer Web Service requiring SMILES now?  SMILES can be generated from the input Molfile on the server side.

**Comment by scilligence** [comment]
Just upgrade web services to latest versions, but the problem is not fixed:

Monomerservice 1.1.5 https://oss.sonatype.org/content/repositories/releases/org/pistoiaalliance/helm/helm2-monomerservice/1.1.5/helm2-monomerservice-1.1.5.war
Webservice 3.0.2 https://oss.sonatype.org/content/repositories/releases/org/pistoiaalliance/helm/helm2-webservice/3.0.2/helm2-webservice-3.0.2.war

![image](https://user-images.githubusercontent.com/19560173/48952403-0c51c200-ef10-11e8-8d6a-d8110213ec6d.png)

**Comment by ClairePA** [comment]
Hi Tony, could you try it again with the natural analogue as - instead of x. The webservices are expecting x. 

I think there could be another issue, but lets sort out one thing at a time. Using - as the natural analogue will show you the parsing error. 

Can you make the next HELM team meeting, so we can go through the issues together? I think we need to do this in order to identify where the problems are.

**Comment by scilligence** [comment]
Tried using - as natural analogue, and I got the same error message.

**Comment by ClairePA** [comment]
Hmm, I think this is why we need to talk it through. I get the parsing error when using -, so we need to check the other parameters and sort this out together.

**Comment by scilligence** [comment]
Is there a way we can check the versions of the two installations?

**Comment by ClairePA** [comment]
Yes, 
The version number for the HELM2monomer service is visible in the Swagger page http://webeditor.openhelm.org:8000/HELM2MonomerService/ for our dev server:

![image](https://user-images.githubusercontent.com/3986896/49280490-4415b800-f482-11e8-9484-0b8acbd14918.png)

and the version number for the HELM2monomerservice is available using the Swagger page at http://webeditor.openhelm.org:8000/WebService/HowToUse.html for our dev server:

![image](https://user-images.githubusercontent.com/3986896/49280659-a7074f00-f482-11e8-9cbc-082de3ebc7b6.png)

![image](https://user-images.githubusercontent.com/3986896/49280707-c3a38700-f482-11e8-934e-39a28df12e0c.png)

but the installation at http://54.83.135.171/ seems to use the right versions, so there must be some other difference. It is really odd. Is there something different about the monomer store? The Dockerfile https://github.com/PistoiaHELM/pistoiahelm.github.com/tree/master/docker shows our precise set up.

**Comment by mjjmmj** [comment]
this still happens with version 1.1.12
any advancements?
