### ISSUE TITLE
Webeditor mol wt calculations are incorrect

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#225]
The following structure is entered as HELM and displays correctly. 
`RNA1{R(A)P.R(C)P.R(G)P}|RNA2{P.R(C)P.R(G)P.R(T)}$RNA1,RNA2,2:pair-9:pair|RNA1,RNA2,5:pair-6:pair|RNA1,RNA2,8:pair-3:pair$$$V2.0`

![image](https://user-images.githubusercontent.com/3986896/46730370-d8804d00-cc7f-11e8-83bf-870b06173f3e.png)
If I copy the molfile of the structure from the structure box and paste it into ChemDraw I get the right structure and the correct mol wt of 1986.21. 
The HELM webservices also calculate a mol wt of 1986.21. 

However the mol wt calculated by the webeditor is incorrect.

**Comment by ClairePA** [comment]
Looking more carefully - I think the webeditor is adding together the mol wts of the individual unconnected monomers so it is always giving a mol wt that is too high. The webeditor mol wt includes the H and OHs that are lost on connection.

**Comment by scilligence** [comment]
Fixed in 2018-10-15 update

**Comment by ClairePA** [comment]
Still wrong. Try `PEPTIDE1{G.G}$$$$V2.0`

The webeditor gives a mol wt of 150 when it should be 135.
