### ISSUE TITLE
Monomer manager new monomer delete button gives error

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#47]
If I start to create a new monomer, but change my mind and click the 'delete' button rather than 'save' I get the error below. 

![image](https://cloud.githubusercontent.com/assets/3986896/19229782/0276a340-8ec8-11e6-9898-5b5d1fa58d03.png)

It doesn't seem to matter how much of the information is present. Perhaps the 'delete' button should be replaced by a cancel that simply doesn't save the entered information?

**Comment by tony-yuan** [comment]
Fixed in 2016-10-10 update

**Comment by ClairePA** [comment]
Tested - not fixed the same behaviour is seen.

**Comment by scilligence** [comment]
fixed in 2017-02-15 update

**Comment by ClairePA** [comment]
Not fixed, but this issue is covered in issue #92. Close here.
