### ISSUE TITLE
Ruleset manager delete button gives an error

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#49]
Steps to recreate:

edit and existing rule (one had previously created).
click the delete button.
'unknown command' error is generated.

**Comment by tony-yuan** [comment]
Fixed in 2016-10-10 update

**Comment by ClairePA** [comment]
Confirmed fixed for existing records. If I use the delete button on a new rule I am creating I get. 

[ERROR]: null. 

I agree that delete makes no sense in this case, but maybe the button should be changed to cancel?

**Comment by tony-yuan** [comment]
In most case, users might not delete a rule.  But if a rule is created by accident, user might ask to delete it.

**Comment by ClairePA** [comment]
In this case though there is no rule to delete since the rule has not been created yet which is why the application can't delete it. This only happens when you are creating a rule not deleting one that has already been saved.

**Comment by scilligence** [comment]
fixed in 2017-02-15 update

**Comment by ClairePA** [comment]
It no longer gives an error if you click delete, but the delete button should be replaced by a cancel button since this is the action the user wants to take if they decide not continue creating a new rule.

**Comment by scilligence** [comment]
Sorry, we updated the system Feb 15, US time.  It is fixed on test site now.

**Comment by ClairePA** [comment]
Nope - I still see a delete button on the dialog box. 
![image](https://cloud.githubusercontent.com/assets/3986896/23025136/be0f91a6-f454-11e6-8a38-19815d83ad73.png)

**Comment by scilligence** [comment]
Same thing. browser cache issue.  Try Ctrl+F5.  I tested it on my computer.  It works fine now.

**Comment by ClairePA** [comment]
Ctrl+F5, tried - same problem as monomer manager. I don't get an error, but still see a delete button and not a cancel one.

**Comment by scilligence** [comment]
I am sorry - it is my fault that we used old js files.  Fixed now.

**Comment by ClairePA** [comment]
Confirmed fixed. Close,
