### ISSUE TITLE
The 'edit monomer' dialogue box should have a cancel button

### ISSUE THREAD

**Issue by ClairePA** [PistoiaHELM/HELMWebEditor#92]
If I edit a monomer and change my mind there is no cancel button to use. Although the x in the top right performs the same function, it should be possible to explicitly choose to cancel the operation. 

![image](https://cloud.githubusercontent.com/assets/3986896/22895853/cf641472-f215-11e6-8660-35a370f318e3.png)

**Comment by scilligence** [comment]
fixed in 2017-02-15 update

**Comment by ClairePA** [comment]
Not fixed - I get the error:

![image](https://cloud.githubusercontent.com/assets/3986896/22974824/10b9fe02-f37c-11e6-88d9-b20842b9d255.png)


Also, the button should be a cancel not a delete button even if the delete button does not cause an error.

**Comment by scilligence** [comment]
1. Sorry.  We just updated the system US morning time Feb 15.   

2. I cannot reproduce the new error. Could you let me know how to reproduce it?

**Comment by ClairePA** [comment]
Tried again today, this time on Firefox, and I still get the error. Steps to reproduce:

Click on the 'new monomer' button.
complete the information as shown.
click delete

![image](https://cloud.githubusercontent.com/assets/3986896/23025716/c451c870-f456-11e6-9852-aea845853b18.png)


Note: the delete button should be replaced by a cancel button.

**Comment by scilligence** [comment]
It is a browser cache issue.  Delete button is removed for New.

**Comment by scilligence** [comment]
Please use Ctrl+F5 to force refresh the browser page.  It works for me.

**Comment by ClairePA** [comment]
Refresh has helped thank you, I no longer get the error. However I still see the delete button and not a cancel one.

![image](https://cloud.githubusercontent.com/assets/3986896/23131165/faf85272-f780-11e6-9e46-6876467e6b10.png)

**Comment by scilligence** [comment]
I am sorry - it is my fault that we used old js files.  Fixed now.

**Comment by ClairePA** [comment]
Cancel button present. Many thanks.
